project:
  type: default
  output-dir: html

format:
  revealjs:
    theme: default
    slide-number: true
    chalkboard: true
    preview-links: auto
    footer: "IS4010: App Development with AI"

execute:
  echo: true
  warning: false
  error: false